version: '3'

services:
  web:
    build: .
    ports:
      - "8000:5000"
    environment:
      - REDIS_HOST=redis
      - PORT=5000
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

#docker-compose up
