base:
  project: winequality-project
  random_state: 50
  target_col: TARGET

logging:
  level: INFO
  format: '%(levelname)s: %(asctime)s: %(message)s'
  log_file: 'logs/get_data.log'

data:
  raw: 'data\raw'
  remote: 'data\remote'



data_source:
  remote_source: remote\winequality-red.csv

load_data:
  raw_dataset_csv: data\raw\winequality.csv

split_data:
  train_path: data\processed\train_wine_quality.csv
  test_path: data\processed\test_wine_quality.csv
  test_size: 0.3

estimators:
  ElasticNet:
    params:
      alpha: 0.9
      l1_ratio: 0.4
model_dir: saved_models

reports:
  params: report\param.json
  scores: report\scores.json

webapp_model_dir: prediction_service\model\model.joblib