base:
  project: winequality-project
  random_state: 50
  target_col: alcohol

logging:
  level: INFO
  format: '%(levelname)s: %(asctime)s: %(message)s'
  log_file: 'logs/data.log'

data:
  raw: 'data\raw'
  remote: 'data\remote'
  cleansed: 'data\cleansed'
  transformed: 'data\transformed'
  

data_source:
  remote_source: remote\winequality-red.csv


split_data:
  train_path: data\processed\train_wine_quality.csv
  test_path: data\processed\test_wine_quality.csv
  test_size: 0.3

model:
  SVR:
    name: SupportVectorRegression
    class: 'models.support_vector_regression_model.train_support_vector_regression_model'
    params:
      kernel: 'rbf'
      C: 1.0

  GradientBoostingRegressor:
    name: GradientBoostingRegression
    class: 'models.gradient_boosting_regression_model.train_gradient_boosting_regression_model'
    params:
      n_estimators: 100
      learning_rate: 0.1

  Ridge:
    name: RidgeRegression
    class: 'models.ridge_regression_model.train_ridge_regression_model'
    params:
      alpha: 1.0

  Lasso:
    name: LassoRegression
    class: 'models.lasso_regression_model.train_lasso_regression_model'
    params:
      alpha: 1.0

  DecisionTreeRegressor:
    name: DecisionTreeRegressor
    class: 'models.decision_tree_regression_model.train_decision_tree_regression_model'



saved_model_dir: saved_models

reports:
  params: report\param.json
  metrics: report\metrics.json
  metrics_history: report\metrics_history.json

webapp_model_dir: prediction_service\model\model.joblib