# Base Configuration
base:
  project: winealcohol-project
  random_state: 50
  target_col: alcohol

# Logging Configuration
logging:
  level: INFO
  format: '%(levelname)s: %(asctime)s: %(message)s'
  log_file: 'logs/data.log'

# Data Paths
data:
  raw: 'data\raw'
  remote: 'data\remote'
  cleansed: 'data\cleansed'
  transformed:
    X: 'data\transformed\X'
    y: 'data\transformed\y'
  
# Data Source Configuration
data_source:
  remote_source: remote\winequality-red.csv

# Schema Configuration
schema:
  input: schema\input_schema.json

# Data Split Configuration
split_data:
  train_path: data\processed\train_wine_quality.csv
  test_path: data\processed\test_wine_quality.csv
  test_size: 0.3

# Model Configuration
model:
  SVR:
    name: SupportVectorRegression
    class: 'models.support_vector_regression_model.train_support_vector_regression_model'
    params:
      kernel: 'rbf'
      C: 1.0

  GradientBoostingRegressor:
    name: GradientBoostingRegression
    class: 'models.gradient_boosting_regression_model.train_gradient_boosting_regression_model'
    params:
      n_estimators: 50
      learning_rate: 0.1

  Ridge:
    name: RidgeRegression
    class: 'models.ridge_regression_model.train_ridge_regression_model'
    params:
      alpha: 1.0

  Lasso:
    name: LassoRegression
    class: 'models.lasso_regression_model.train_lasso_regression_model'
    params:
      alpha: 1.0

  DecisionTreeRegressor:
    name: DecisionTreeRegressor
    class: 'models.decision_tree_regression_model.train_decision_tree_regression_model'

# Saved Model and Scaler Directories
saved_model_dir: model_artifacts\saved_models 
scaler_dir: model_artifacts\scaler

# Reports Configuration
reports:
  reports: report
  params: report\params.json
  metrics: report\metrics.json
  metrics_history: report\metrics_history.json

# Prediction App Configuration
prediction_app:
  root_dir: prediction_app
  model: prediction_app\prediction_resources\serving_models
  scaler: prediction_app\prediction_resources\scaler
